# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432
    volumes:
      - "./db:/docker-entrypoint-initdb.d/"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080

  smtp:
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025
      - 8025

  service:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "8000:8080"
    depends_on:
      - db
    environment:
      SMTP_PORT: 1025
